# Configuration file for the toy example
plotting:
  # An optional key to specify the font for matplotlib plots (comment out if not needed)
  # e.g.,
  # font: Calibri
  font:
global_paths:
  # input_folder should point to a directory that has the folders obs, jacobians, transcom, etc
  # spaces in the folder name are OK, but there *must* be a space after the colon, e.g.,
  # input_folder: /mydrive/my name/data
  input_folder: 
  # where you want the output to go, create this if you don't have it
  # same rules apply as input_folder, e.g., the following is OK
  # output_folder: /mydrive/another drive/my name/output
  output_folder:
retrieval:
  # the full path of absco.h5, e.g.,
  # absco_table: /mydrive/who knows/input_data/absco.h5
  absco_table:
observations:
  obspack_folder: /tmp/ssim-ghg-data/observation_example_datasets/obspack_co2_1_GLOBALVIEWplus_v9.1_2023-12-08/data/nc/
  obspack_surface_code: co2_lef_tower-insitu_1_allvalid
  obspack_surface_heights: 30,122,396
  obspack_aircraft_code: co2_lef_aircraft-pfp_1_allvalid
  tccon_folder: /tmp/ssim-ghg-data/observation_example_datasets/tccon/
  tccon_site: pa
  ameriflux_file: /tmp/ssim-ghg-data/observation_example_datasets/AMF_US-PFa_BASE-BADM_28-5/AMF_US-PFa_BASE_HR_28-5.csv
  